# Pandas

Pandas word come from panel data , Mean about data. Pandas is Used in most of top Computer science fields like Data science , Machine learning, AI engineering and etc. It is used for data cleaning , organizing, Data information , Data summary , also used for getting key insights from data and manipulation.

In [2]:
# Install Pandas using commands `pip install pandas` 

import pandas
# But instead of importing pandas and using whole word as class developer use pd short for pandas.
import pandas as pd

data = {
    "name": ["jarair","haseeb","hamza", "farhan","ahmad"],
    "Age": [17,18,29,10,27],
    "class" : [11,12,10,8,9]
    
}

# Important: Series is 1D data so i use one column
df = pd.Series(data["name"], index=["class1","class2","class3","class4","class5"])


# .loc is label based filtering
df.loc["class3"]

# .iloc index based
df.iloc[0]


# Codition adding
df = pd.Series(data["Age"])
df[df > 17]

1    18
2    29
4    27
dtype: int64

## Creating and Manipulating DataFrames (Two-Dimensional Data)

A **DataFrame** is a two-dimensional labeled grid, table, or tabular data structure with rows and columns.

In [3]:
data = {
    "name": ["jarair","haseeb","hamza", "farhan","ahmad"],
    "Age": [17,18,29,10,27],
    "class" : [11,12,10,8,9]
    
}

# Important: Dataframe is 2D Data
df = pd.DataFrame(data, index=["class1","class2","class3","class4","class5"])


# .loc is label based filtering
df.loc["class3"]

# .iloc index based
df.iloc[0]

# Adding new Column
df["Marks"] = [400,355,677,909,1021]

# Adding Row
new_member = pd.DataFrame({
    "name": ["mohsin"], 
    "Age":80, 
    "class":34, 
    "Marks": [100]
}, index=["class6"])

df = pd.concat([df,new_member])
df

          name  Age  class  Marks
class1  jarair   17     11    400
class2  haseeb   18     12    355
class3   hamza   29     10    677
class4  farhan   10      8    909
class5   ahmad   27      9   1021
class6  mohsin   80     34    100

In [4]:
import pandas as pd


# 2. Display the original Data
print("=== ORIGINAL DATAFRAME ===")
display(df)
print("\n" + "="*50 + "\n")

# Mean/Average
print("--- 1. Mean (Average) ---")
display(df.mean(numeric_only=True))
print("\n")

# Sum
print("--- 2. Sum ---")
display(df.sum(numeric_only=True))
print("\n")

# Minimum
print("--- 3. Minimum ---")
display(df.min())
print("\n")

# Maximum
print("--- 4. Maximum ---")
display(df.max())
print("\n")

# Count
print("--- 5. Count ---")
display(df.count())
print("\n")

# Column Aggregation
print("--- 6. Column Aggregation ---")
avg_marks = df['Marks'].mean()
print(f"The average of Marks column is: {avg_marks}")
print("\n" + "="*50 + "\n")

# Groupby Function
print("--- 7. Groupby (Average Age and Marks per Class) ---")
display(df.groupby('class')[['Age', 'Marks']].mean())

=== ORIGINAL DATAFRAME ===

          name  Age  class  Marks
class1  jarair   17     11    400
class2  haseeb   18     12    355
class3   hamza   29     10    677
class4  farhan   10      8    909
class5   ahmad   27      9   1021
class6  mohsin   80     34    100

==================================================

--- 1. Mean (Average) ---

Age       30.166667
class     14.000000
Marks    577.000000
dtype: float64

--- 2. Sum ---

Age       181
class      84
Marks    3462
dtype: int64

--- 3. Minimum ---

name     ahmad
Age         10
class        8
Marks      100
dtype: object

--- 4. Maximum ---

name     mohsin
Age          80
class        34
Marks      1021
dtype: object

--- 5. Count ---

name     6
Age      6
class    6
Marks    6
dtype: int64

--- 6. Column Aggregation ---
The average of Marks column is: 577.0

==================================================

--- 7. Groupby (Average Age and Marks per Class) ---

        Age   Marks
class
8      10.0   909.0
9      27.0  1021.0
10     29.0   677.0
11     17.0   400.0
12     18.0   355.0
34     80.0   100.0

In [21]:

data = pd.read_csv("Employee Sample Data 1.csv",encoding="latin1",index_col="Employee ID")

df = pd.DataFrame(data)

# Filtering And removing % sign
# df["Bonus %"] = df["Bonus %"].str.rstrip('%').astype('float')


# df.drop(columns="Exit Date")
# df = df.dropna(subset="Exit Date")
# df = df[df["Department"]!="IT"]
# df = df[df["Age"] < 40]
df

,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
Employee ID,,,,,,,,,,,,,
E02002,Kai Le,Controls Engineer,Engineering,Manufacturing,Male,Asian,47.0,2/5/2022,"$92,368",0%,United States,Columbus,NaN
E02003,Robert Patel,Analyst,Sales,Corporate,Male,Asian,58.0,10/23/2013,"$45,703",0%,United States,Chicago,NaN
E02004,Cameron Lo,Network Administrator,IT,Research & Development,Male,Asian,34.0,3/24/2019,"$83,576",0%,China,Shanghai,NaN
E02005,Harper Castillo,IT Systems Architect,IT,Corporate,Female,Latino,39.0,4/7/2018,"$98,062",0%,United States,Seattle,NaN
E02006,Harper Dominguez,Director,Engineering,Corporate,Female,Latino,42.0,6/18/2005,"$175,391",24%,United States,Austin,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
E02250,Mila Han,Manager,Sales,Manufacturing,Female,Asian,54.0,11/14/2009,"$128,791",6%,United States,Miami,NaN
E02251,Genesis Herrera,Manager,IT,Research & Development,Female,Latino,34.0,10/3/2015,"$126,898",10%,Brazil,Manaus,NaN
E02252,Olivia Vazquez,Network Engineer,IT,Specialty Products,Female,Latino,53.0,4/13/2020,"$93,053",0%,Brazil,Sao Paulo,NaN
E02253,Leilani Ng,Systems Analyst,IT,Corporate,Female,Asian,48.0,9/19/2011,"$50,513",0%,United States,Seattle,10/30/2019
E02254,Olivia Mendoza,Sr. Account Representative,Sales,Corporate,Female,Latino,43.0,5/7/2017,"$86,533",0%,United States,Columbus,NaN